### ISSUE TITLE
URGENT MATTER

### ISSUE THREAD

**Issue by adrianstrom** [Brakistad/homepage#1]
Dear Brakistad,

Today I visited your homepage.
I was impressed when I was met by a canvas. My dream of following the footsteps of the great Van Gogh could finally come true. A canvas was something I quite simply couldn't afford because of the electricity bills.

I started drawing, and wasn't happy with the result. So I wanted to try again. I clicked the SPACEBAR. I was absouletely astounded when trying again that my old drawing came back to life.

This is serious business. How could you do this? You've ruined my chances of becoming a great painter. Shame on you.

Sincerely,
A discouraged painter

**Comment by Brakistad** [comment]
I have to had the pleasure of being suprised by the canvas history constantly coming back.
Even though this is a feature that i planned for and got, just as i wanted.
I created a version in my own private environment, where this feature was no more. All gone.
This caused me to question the meaning of my spontanious features, and i went on a rampage to remove other features, like Little text, no seperation on segregated classes like header, body and footer.

I went on and on, removing and shuffling features.
Never to find any stable ground to settle my canvas.

I will soon release the remains of this battlefield.
But first, i need to mourn the fallen features...

Kind Regards,
A canvas placer
